# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('field_visit', 'Field visit to Kachieng cluster'), ('cluster_meeting', 'Cluster meeting in Kachieng'), ('re_evidence', 'Re-collect evidence'), ('print_advisory', 'Print advisory for delivery')], max_length=40)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=40)),
                ('ward', models.CharField(default='Kachieng', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_advisory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks', to='advisories.advisory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
