# Generated by Django 5.1.15 on 2026-10-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', help_text='Account approval status. Pending users cannot access operational routes.', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text="Office/organization the officer belongs to (e.g. 'Nyatike Sub-County Agricultural Office').", max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('extension_officer', 'Extension Officer'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], default='viewer', help_text='Role requested during registration. Does NOT grant privileges until approved.', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Officer email for notifications (if email is configured).', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('extension_officer', 'Extension Officer'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], default='viewer', help_text='Effective operational role, set by an administrator after account approval.', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_county',
            field=models.CharField(default='Nyatike', help_text="Officer's assigned sub-county.", max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='ward',
            field=models.CharField(default='Kachieng', help_text="Officer's assigned ward.", max_length=80),
        ),
    ]
