# Generated by Django 5.1.15 on 2026-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(default='maize', max_length=80)),
                ('market', models.CharField(default='Migori-Town', max_length=120)),
                ('price_kes_per_90kg', models.FloatField()),
                ('observation_date', models.DateField()),
                ('trend', models.CharField(blank=True, help_text="One of: 'rising', 'falling', 'stable', 'unknown'.", max_length=40)),
                ('source', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-observation_date',),
            },
        ),
    ]
