# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_label', models.CharField(blank=True, help_text='Free-text area label if FK missing.', max_length=120)),
                ('period', models.CharField(choices=[('last_30_days', 'Last 30 days'), ('last_7_days', 'Last 7 days'), ('10_day_forecast', '10-day forecast'), ('seasonal_outlook', 'Seasonal outlook')], max_length=40)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('forecast_summary', models.TextField(blank=True)),
                ('onset_status', models.CharField(blank=True, help_text="One of: 'onset_confirmed', 'onset_delayed', 'false_start', 'unknown'.", max_length=80)),
                ('confidence', models.CharField(default='medium', help_text='low / medium / high — qualitative confidence.', max_length=20)),
                ('source', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_date', models.DateField()),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weather_signals', to='geography.subcounty')),
            ],
            options={
                'ordering': ('-source_date', '-retrieved_at'),
            },
        ),
    ]
