# Generated by Django 5.1.15 on 2026-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersignal',
            name='retrieved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
