# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=30, unique=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loam', 'Loam'), ('clay', 'Clay'), ('silt', 'Silt-loam'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('irrigation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='clusters.household')),
            ],
        ),
        migrations.CreateModel(
            name='CropSeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text="e.g. '2024 short_rains'", max_length=40)),
                ('crop', models.CharField(default='maize', max_length=80)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial_failure', 'Partial failure'), ('total_failure', 'Total failure'), ('delayed_planting', 'Delayed planting'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('yield_band', models.CharField(choices=[('low', 'Low (<1 t/ha)'), ('medium', 'Medium (1–3 t/ha)'), ('high', 'High (>3 t/ha)'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_records', to='plots.plot')),
            ],
            options={
                'ordering': ('-season', 'plot'),
                'unique_together': {('plot', 'season', 'crop')},
            },
        ),
    ]
