# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('plant', 'Planting window suitable'), ('delay', 'Delay planting, verify local onset'), ('verify_locally', 'Verify locally'), ('pest_monitoring', 'Pest monitoring'), ('data_gap', 'Data gap — officer follow-up')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('needs_evidence', 'Needs more evidence')], default='draft', max_length=40)),
                ('summary', models.CharField(max_length=240)),
                ('body', models.TextField(help_text='Structured advisory text with sources.')),
                ('confidence', models.CharField(default='medium', max_length=20)),
                ('limitations', models.TextField(blank=True)),
                ('county', models.CharField(default='Migori', max_length=80)),
                ('sub_county', models.CharField(default='Nyatike', max_length=80)),
                ('ward', models.CharField(default='Kachieng', max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('model_run_id', models.CharField(blank=True, max_length=120)),
                ('model_prompt_hash', models.CharField(blank=True, max_length=64)),
                ('generation_mode', models.CharField(default='fallback_template', help_text="One of: 'ollama_qwen', 'fallback_template'.", max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisories', to='clusters.farmercluster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdvisoryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text="One of: 'plot_history', 'crop_calendar', 'weather', 'pest', 'market', 'other'.", max_length=40)),
                ('source_ref', models.CharField(help_text="Human-readable reference to the source record (e.g. 'WeatherSignal#12').", max_length=160)),
                ('claim', models.TextField(help_text='What this evidence supports in the advisory.')),
                ('is_stale', models.BooleanField(default=False)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('advisory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='advisories.advisory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['status', 'cluster'], name='advisories__status_1e1708_idx'),
        ),
    ]
