# Generated by Django 5.1.15 on 2026-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='generation_seconds',
            field=models.FloatField(blank=True, help_text='Wall-clock seconds spent in the draft_advisory node (model call or fallback).', null=True),
        ),
    ]
