# Generated by Django 5.1.15 on 2026-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0003_advisory_scope_and_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryevidence',
            name='source_observed_at',
            field=models.CharField(blank=True, help_text='Source observation or publication date — not the same as retrieval time.', max_length=40),
        ),
    ]
