# Generated by Django 5.1.15 on 2026-10-06 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0004_alter_advisoryevidence_source_observed_at'),
        ('clusters', '0002_farmercluster_coordinates_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Set when an advisory is soft-deleted. NULL = active.', null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Officer who soft-deleted this advisory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisory',
            name='deletion_reason',
            field=models.CharField(blank=True, help_text='Reason for soft-deletion (internal officer note).', max_length=200),
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['deleted_at'], name='advisories__deleted_a6b644_idx'),
        ),
    ]
