# Generated by Django 5.1.15 on 2026-10-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_farmercluster_coordinates_verified_and_more'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coordinate_source', models.CharField(help_text="e.g. 'OpenStreetMap Nominatim'", max_length=120)),
                ('source_feature_id', models.CharField(blank=True, help_text='OSM feature id', max_length=120)),
                ('source_url', models.URLField(blank=True, help_text='Link to the OSM feature')),
                ('retrieved_at', models.DateTimeField(auto_now=True)),
                ('coordinate_type', models.CharField(choices=[('settlement_reference', 'Settlement reference'), ('landmark_reference', 'Landmark reference'), ('official_centroid', 'Official centroid'), ('owner_confirmed_reference', 'Owner confirmed reference'), ('synthetic', 'Synthetic')], default='settlement_reference', max_length=40)),
                ('verification_status', models.CharField(choices=[('candidate', 'Candidate (awaiting review)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='candidate', max_length=40)),
                ('verified_by', models.CharField(blank=True, max_length=160)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locality_coordinate', to='clusters.farmercluster')),
            ],
            options={
                'ordering': ('cluster__cluster_id',),
            },
        ),
    ]
