# Generated by Django 5.1.15 on 2026-10-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_advisoryrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advisoryrun',
            new_name='agents_advi_request_ed6486_idx',
            old_name='agents_advi_request_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='advisoryrun',
            new_name='agents_advi_cluster_81b909_idx',
            old_name='agents_advi_cluster_8c2f1a_idx',
        ),
    ]
