# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(default='maize', max_length=80)),
                ('zone_label', models.CharField(blank=True, help_text="Free-text zone label used when zone FK is not present (e.g. 'Migori-Low-Mid').", max_length=120)),
                ('season', models.CharField(choices=[('short_rains', 'Short rains (Sep–Dec)'), ('long_rains', 'Long rains (Mar–Jul)')], default='short_rains', max_length=40)),
                ('planting_window_start', models.DateField()),
                ('planting_window_end', models.DateField()),
                ('activities', models.JSONField(default=list, help_text='Ordered list of recommended activities.')),
                ('source', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_date', models.DateField()),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='geography.agroclimaticzone')),
            ],
            options={
                'ordering': ('-source_date',),
                'unique_together': {('crop', 'zone_label', 'season')},
            },
        ),
    ]
