# Generated by Django 5.1.15 on 2026-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropcalendar',
            options={'ordering': ('-publication_date', '-source_date')},
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='coverage_level',
            field=models.CharField(blank=True, help_text="One of: 'national', 'regional', 'county', 'sub-county', 'ward', 'locality', 'point'.", max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='evidence_passage_reference',
            field=models.CharField(blank=True, help_text="Page/section reference for the supporting passage, e.g. 'p. 17, section 3.2'.", max_length=200),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='extraction_review_status',
            field=models.CharField(choices=[('not_extracted', 'Not extracted (metadata only)'), ('metadata_only', 'Metadata only'), ('passages_extracted', 'Passages extracted under licence'), ('officer_reviewed', 'Officer reviewed')], default='not_extracted', max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='extraction_version',
            field=models.CharField(blank=True, help_text='Extraction code version used to ingest.', max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='geographic_scope',
            field=models.CharField(blank=True, help_text="Free-text scope label as published, e.g. 'Lake Victoria Basin', 'Migori County', 'national'.", max_length=160),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='When the system last checked for a new edition.', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='licence_or_permission_basis',
            field=models.CharField(blank=True, help_text="Basis for reuse, e.g. '© KALRO 2021 — all rights reserved; permission pending', 'MIT licence', 'Public; cite with attribution'.", max_length=200),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='local_applicability_review',
            field=models.CharField(choices=[('not_reviewed', 'Not reviewed by local officer'), ('reviewed', 'Reviewed by local officer'), ('rejected', 'Reviewed and rejected for this area')], default='not_reviewed', max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='observed_from',
            field=models.DateField(blank=True, help_text='Start of the observation period (for station data).', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='observed_to',
            field=models.DateField(blank=True, help_text='End of the observation period (for station data).', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='permission_status',
            field=models.CharField(choices=[('open_data', 'Open data (clearly reusable licence)'), ('attribution_only', 'Public; cite with attribution'), ('permission_pending', 'Permission pending'), ('restricted', 'Restricted (do not reproduce)')], default='attribution_only', max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='product_type',
            field=models.CharField(blank=True, help_text="Authority's product name, e.g. '7 Days Forecast', 'KCEP-CRAL Maize Extension Manual', 'Pest factsheet', 'Officer field report'.", max_length=80),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='publication_date',
            field=models.DateField(blank=True, help_text='When the authority issued the document.', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='raw_document_checksum',
            field=models.CharField(blank=True, help_text='SHA-256 of the source document, if stored.', max_length=128),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='source_authority',
            field=models.CharField(blank=True, help_text="Issuing authority, e.g. 'Kenya Meteorological Department', 'KALRO', 'KEPHIS', 'Officer field report'.", max_length=120),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='source_document_id',
            field=models.CharField(blank=True, help_text='Document/notice ID assigned by the authority, if known.', max_length=120),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='synthetic_flag',
            field=models.CharField(choices=[('real', 'Real (sourced from official publication)'), ('synthetic', 'Synthetic test scenario'), ('officer_report', 'Officer field report')], default='synthetic', help_text='Synthetic records are kept for tests/demo and are never relabelled as real.', max_length=40),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Forecast validity start (for forecasts).', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Forecast validity end (for forecasts).', null=True),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='verification_status',
            field=models.CharField(choices=[('current_official', 'Current official bulletin'), ('regional_context', 'Regional context'), ('background_reference', 'Background reference (not current outbreak)'), ('officer_field_report', 'Officer field report'), ('historical', 'Historical notice (no longer current)'), ('synthetic', 'Synthetic test scenario'), ('no_current_notice', 'No current notice available')], default='synthetic', help_text='Honest availability state — see docs/governance/source_access_register.md.', max_length=40),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='activities',
            field=models.JSONField(default=list, help_text='Ordered list of recommended activities. Store ONLY if licence permits reproduction. Otherwise leave empty.'),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='planting_window_end',
            field=models.DateField(blank=True, help_text='Planting window end. Leave NULL when the source does not specify LOCAL dates for this zone.', null=True),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='planting_window_start',
            field=models.DateField(blank=True, help_text='Planting window start. Leave NULL when the source does not specify LOCAL dates for this zone.', null=True),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='source_date',
            field=models.DateField(blank=True, help_text='Legacy alias for publication_date.', null=True),
        ),
    ]
