# Generated by Django 5.1.15 on 2026-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(default='maize', max_length=80)),
                ('pest', models.CharField(max_length=120)),
                ('county', models.CharField(default='Migori', max_length=80)),
                ('region', models.CharField(default='Nyanza', max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='moderate', max_length=20)),
                ('advisory', models.TextField()),
                ('source', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_date', models.DateField()),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-source_date',),
            },
        ),
    ]
