# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('tool_name', models.CharField(blank=True, max_length=80)),
                ('inputs_summary', models.JSONField(blank=True, default=dict)),
                ('outputs_summary', models.JSONField(blank=True, default=dict)),
                ('approval_status', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['tool_name', 'created_at'], name='audit_audit_tool_na_42bbe8_idx')],
            },
        ),
    ]
