# Generated by Django 5.1.15 on 2026-10-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(help_text="Human-readable cluster code e.g. 'KACH-01'.", max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('representative', models.CharField(blank=True, help_text='Synthetic representative name.', max_length=160)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='geography.extensionoffice')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='geography.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=30, unique=True)),
                ('head_of_household', models.CharField(blank=True, help_text='Pseudonymous identifier. No real names used in synthetic fixtures.', max_length=160)),
                ('phone_e164', models.CharField(blank=True, help_text='Synthetic phone for demo only.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='clusters.farmercluster')),
            ],
            options={
                'ordering': ('household_id',),
            },
        ),
    ]
