# Generated by Django 5.1.15 on 2026-10-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercluster',
            name='coordinates_verified',
            field=models.BooleanField(default=False, help_text='True only if coordinates are verified real; False if synthetic or missing.'),
        ),
        migrations.AddField(
            model_name='farmercluster',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality name (e.g. Sori, Kiranda). Confirmed by project owner; no government classification claimed.', max_length=120),
        ),
    ]
